###############################
#########DATABASE##############
###############################
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/user-management
    username: root
    password: mysql
############################
#######HIKARI##############
############################
    hikari:
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 1800000
      minimum-idle: 10
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
  ###############################
  ######MAIL CONFIG##############
  ###############################
  mail:
    host: 172.17.0.3
    port: 1025
  sql:
    init:
      mode: never
server:
  error:
    include-message: always
###############################
##############JWT##############
###############################
jwt:
  public:
    key: file:/home/farzad/Desktop/fileLinux/Maktab/Tamrin/simple_user_management/src/main/resources/public.pub
############################
#######SWAGGER##############
############################
openapi:
  service:
    title: Simple_user_management
    version: 1.0
    url: http://localhost:8080
