spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/user-management
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  mail:
    host: 172.17.0.3
    port: 1025
  sql:
    init:
      mode: always
server:
  error:
    include-message: always